//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XavierSite.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public string DeliveryAddress { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Status OrderStatus { get; set; }
        public Nullable<decimal> Discout { get; set; }
    
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
